include:
  - template: Auto-DevOps.gitlab-ci.yml

image: node:current-alpine

pages:
  stage: staging
  script:
    - cd docs
    - yarn install
    - yarn build:gitlab
  artifacts:
      paths:
        - public
  only:
    - master