name: Continuous Deployment
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: bnussman/api:latest
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'api'
          namespace: 'beep'
          chart: '.github/helm/'
          token: '${{ github.token }}'
          value-files: >-
          [
            ".github/helm/values.yaml", 
          ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'