name: ci

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-workspace.yaml') }}
      - run: pnpm i --frozen-lockfile
      - run: pnpm build:api
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-workspace.yaml') }}
      - run: pnpm i --frozen-lockfile
      - run: pnpm --filter @beep/website typecheck
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-workspace.yaml') }}
      - run: pnpm --frozen-lockfile
      - run: pnpm --filter @beep/app typecheck
